version: "3.7"
services:
  app:
    build:
      args:
        user: josue
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pruebahomeland
    container_name: pruebahomeland-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pruebahomelad

  db:
    image: mysql:5.7
    container_name: pruebahomeland-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - pruebahomelad

  nginx:
    image: nginx:alpine
    container_name: pruebahomeland-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pruebahomelad

networks:
  pruebahomelad:
    driver: bridge
